export const COMPARISON_CORE_PACKAGE_NAME = '@difflens/comparison-core';

export { compareDatasets, validateComparisonInput } from './compare';
export type {
  AddedRecordResult,
  ChangedRecordResult,
  ComparisonConfiguration,
  ComparisonDiagnostic,
  ComparisonDiagnosticCode,
  ComparisonDiagnosticExample,
  ComparisonDiagnosticSeverity,
  ComparisonOptions,
  ComparisonOutcome,
  ComparisonResult,
  ComparisonSide,
  ComparisonSummary,
  ComparisonValidation,
  DiagnosticRecordReference,
  FieldDifference,
  FieldDifferenceKind,
  KeyConfiguration,
  NormalizedDataset,
  NormalizedDatasetWarning,
  NormalizedObject,
  NormalizedPrimitive,
  NormalizedRecord,
  NormalizedSourceLocation,
  NormalizedValue,
  RemovedRecordResult,
  SourceWarnings,
  UnchangedRecordResult,
  UnmatchableReason,
  UnmatchableRecord,
  ValuePresence,
} from './contracts';
